; xdebug
xdebug.mode=debug,coverage,develop,profile
xdebug.client_port=9000
xdebug.client_host=host.docker.internal
xdebug.discover_client_host=1
xdebug.log_level=10

; dev overrides (DX - Developer Experience)
display_errors=On
display_startup_errors=On
memory_limit=256M
